# Generated by Django 3.2.12 on 2022-04-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_diary_table_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary_table',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
